name: Test

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      TZ: 'Europe/London'
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
          
      - name: Setup PostgreSQL
        uses: harmon758/postgresql-action@v1
        with:
          postgresql db: test_db
          postgresql user: admin
          postgresql password: password
          
      - name: Install dependencies
        run: npm install
        
      - name: Run tests
        env:
          PGDATABASE: test_db
          PGUSER: admin
          PGPASSWORD: password
        run: npm test
